# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "UpdateKernel"
  config.ssh.username = "root"
  config.ssh.password = "vagrant"
  config.ssh.insert_key = "true"

  config.vm.network "forwarded_port", guest: 80, host: 88, host_ip: "127.0.0.1"

  config.vm.network "private_network", ip: "192.168.56.150" 
  config.vm.hostname = "test" 
  
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end

end
